title: Blog Demo - Can We Uncomment HTML Comments with Javascript
description: Blog Demo - Can We Uncomment HTML Comments with Javascript
email: kemal.yilmaz@tutanota.com
baseurl: "/blog-demo-dom-nodes-are-expensive"
twitter_username: xkema
github_username:  xkema
include:
  - _pages
# excludes heavy-weight customizations folder for build performance (they sould be handled manually)
exclude:
  - _pages/memory-usage/customizations/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  style: compressed
strict_front_matter: true
timezone: Asia/Istanbul
disable_disk_cache: true
ignore_theme_config: true