title: Blog Demo - Can We Uncomment HTML Comments with Javascript
description: Blog Demo - Can We Uncomment HTML Comments with Javascript
email: kemal.yilmaz@tutanota.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xkema
github_username:  xkema
include:
  - _pages
# exclude:
#   - _pages/performance-optimization/customizations
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  style: compressed
strict_front_matter: true
timezone: Asia/Istanbul
disable_disk_cache: true
ignore_theme_config: true
livereload: true